# This checks whether the code is formatted according to PEP8 standards
# It does this using the black code formatter
name: Black code formatter

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable


