name: Check Documentation Build
on:
  - pull_request
  - push
  - workflow_dispatch

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.4.2"
  POETRY_URL: https://install.python-poetry.org


jobs:
  build-documentation:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      # Use the -W flag in the sphinx-build command to treat warnings as errors.
      # Compile the sphinx doc. If no errors or warnings arise, this will result in a green "succeed" mark in GH Actions
      # Otherwise, GH Action will fail.
      - name: Compile Sphinx Documentation (Check for errors)
        run: |
          cd docs/
          sphinx-build -b html . _build -W -a
