name: Unit Tests
on:
  - pull_request
  - push
  - workflow_dispatch
  -
jobs:
  # Label
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: [ "3.9 3.10 3.11 3.12" ]
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run Tests
        run: | 
          pytest
        env:
          # Add the `src` directory to the PYTHONPATH
          PYTHONPATH: src/:$PYTHONPATH:tests/
          # Add environment variables (used to tell the code it is in testing mode for example) here
          TESTING: "True"


